### ISSUE TITLE
other user profile response wrong data

### ISSUE THREAD

**Issue by JAmoMES** [teletubby-v-2/front#37]
<img width="470" alt="Screen Shot 2021-09-08 at 4 12 57 AM" src="https://user-images.githubusercontent.com/77198497/132411639-c7a49aab-63bc-4d4f-8c46-1e41ad0409c3.png">

- sociallink เป็นของตัวเอง และ overflow 
- ให้แก้เป็นไม่ต้องมีลิ้งแทน แต่กดไอคอนหรือชื่อให้ลิ้งไปหาลิ้งนั้น
- กดเข้าหา userId ตัวเองไม่ได้ดักให้ลิ้งกลับมาที่ /profile หรือจิงๆ แล้วควรใช้พาทเดียวกันเลย

**Comment by JAmoMES** [comment]
@numkhang

**Comment by numkhang** [comment]
แก้แล้ว check หน่อยว่ามีปัญหาไหม
